site_name: transcriber
repo_url: https://github.com/dscoular/transcriber
site_url: https://dscoular.github.io/transcriber
site_description: A python script which uses whisper to transcribe videos and outputs SRT files.
site_author: Doug Scoular
edit_uri: edit/main/docs/
repo_name: dscoular/transcriber
copyright: |
  Copyright &copy; 2025 Doug Scoular<br>
  All rights reserved. Licensed under the MIT license.
nav:
  - Home: index.md
  - 🚀 Getting Started: getting-started.md
  - Using Docker: docker.md
  - Modules: modules.md
  - Coverage: coverage.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/transcriber"]
  - coverage:
      page_path: coverage
      html_report_dir: htmlcov

theme:
  name: material
  features:
    - tabs: true
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dscoular/transcriber
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/transcriber

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
